"""Aviation packs: commercial airline operations and Part-145 MRO."""

from .base import CodeSystem, DocType, Pack, Workflow

# ---------------------------------------------------------------------------
# ATA iSpec 2200 chapter numbering.
#
# This is the spine of every aviation maintenance document. A task card, an
# Airworthiness Directive, an MEL item and a Service Bulletin are all filed by
# ATA chapter, so the same controlled vocabulary threads through both packs
# below and becomes the strongest edge type in the aerospace graph.
# ---------------------------------------------------------------------------

ATA_CHAPTERS = (
    ("05", "Time Limits / Maintenance Checks"),
    ("06", "Dimensions and Areas"),
    ("07", "Lifting and Shoring"),
    ("08", "Leveling and Weighing"),
    ("09", "Towing and Taxiing"),
    ("10", "Parking, Mooring and Storage"),
    ("11", "Placards and Markings"),
    ("12", "Servicing"),
    ("20", "Standard Practices — Airframe"),
    ("21", "Air Conditioning"),
    ("22", "Auto Flight"),
    ("23", "Communications"),
    ("24", "Electrical Power"),
    ("25", "Equipment and Furnishings"),
    ("26", "Fire Protection"),
    ("27", "Flight Controls"),
    ("28", "Fuel"),
    ("29", "Hydraulic Power"),
    ("30", "Ice and Rain Protection"),
    ("31", "Indicating and Recording"),
    ("32", "Landing Gear"),
    ("33", "Lights"),
    ("34", "Navigation"),
    ("35", "Oxygen"),
    ("36", "Pneumatic"),
    ("38", "Water and Waste"),
    ("44", "Cabin Systems"),
    ("45", "Central Maintenance System"),
    ("46", "Information Systems"),
    ("49", "Airborne Auxiliary Power"),
    ("51", "Standard Practices — Structures"),
    ("52", "Doors"),
    ("53", "Fuselage"),
    ("54", "Nacelles and Pylons"),
    ("55", "Stabilizers"),
    ("56", "Windows"),
    ("57", "Wings"),
    ("71", "Power Plant"),
    ("72", "Engine"),
    ("73", "Engine Fuel and Control"),
    ("74", "Ignition"),
    ("75", "Bleed Air"),
    ("76", "Engine Controls"),
    ("77", "Engine Indicating"),
    ("78", "Exhaust"),
    ("79", "Oil"),
    ("80", "Starting"),
)

# IATA AHM 730/731 delay codes. Weighted realistically in the generator —
# ramp, technical and reactionary delays dominate real operations.
IATA_DELAY_CODES = (
    ("11", "Late check-in, acceptance after deadline"),
    ("14", "Oversales, booking errors"),
    ("15", "Boarding, missing checked-in passenger at gate"),
    ("18", "Baggage processing"),
    ("31", "Aircraft documentation late"),
    ("32", "Loading and unloading"),
    ("33", "Loading equipment"),
    ("35", "Aircraft cleaning"),
    ("36", "Fuelling and defuelling"),
    ("41", "Aircraft defects"),
    ("42", "Scheduled maintenance, late release"),
    ("46", "Aircraft change for technical reasons"),
    ("51", "Damage during ground operations"),
    ("55", "Departure control system outage"),
    ("61", "Flight plan late"),
    ("62", "Operational requirements, fuel or load"),
    ("63", "Late crew boarding"),
    ("71", "Departure station weather"),
    ("75", "De-icing"),
    ("87", "Airport facilities"),
    ("93", "Aircraft rotation, late arrival"),
    ("96", "Operations control, rerouting"),
    ("99", "Other"),
)


AIRLINES = Pack(
    slug="q-airlines",
    spine="aircraft",
    tenant="Q-Airlines",
    industry="Commercial Airline Operations",
    tagline="Network carrier · 214 aircraft · 68 stations",
    accent="#0B66E1",
    units=(
        "Flight Operations",
        "Crew Operations",
        "Crew Scheduling",
        "Ground Operations",
        "Station Operations",
        "System Operations Control",
        "Maintenance Operations Control",
        "Flight Dispatch",
        "Network Planning",
        "Revenue Management",
        "Cargo Operations",
        "Inflight Services",
        "Technical Operations",
        "Load Control",
        "Safety and SMS",
    ),
    roles=(
        "Director of Operations",
        "Chief Pilot",
        "Manager, Crew Planning",
        "Duty Manager Operations",
        "Aircraft Dispatcher",
        "Station Manager",
        "Load Controller",
        "MOC Controller",
        "Manager, Ground Safety",
        "Director, Safety and Compliance",
    ),
    systems=(
        "Meridian PSS",
        "Meridian DCS",
        "CrewLink",
        "OpsBridge OCC",
        "LoadStar Weight & Balance",
        "SafetyNet SMS",
    ),
    doc_types=(
        DocType(
            key="fom",
            name="Flight Operations Manual — Chapter",
            abbrev="FOM",
            id_grammar="FOM",
            weight=0.9,
            authority="14 CFR Part 121.133",
            system="OpsBridge OCC",
            sections=(
                "Purpose and Applicability",
                "Regulatory Basis",
                "Operational Limitations",
                "Crew Responsibilities",
                "Normal Procedures",
                "Non-Normal Procedures",
                "Recording and Reporting",
            ),
        ),
        DocType(
            key="gom",
            name="Ground Operations Manual — Procedure",
            abbrev="GOM",
            id_grammar="GOM",
            weight=1.2,
            authority="IATA IGOM / AHM",
            system="OpsBridge OCC",
            sections=(
                "Purpose and Scope",
                "Applicability by Station",
                "Safety Precautions",
                "Equipment Required",
                "Procedure Steps",
                "Turnaround Milestones",
                "Deviation Reporting",
            ),
        ),
        DocType(
            key="sop",
            name="Station Operating Procedure",
            abbrev="SOP",
            id_grammar="STN",
            weight=1.5,
            authority="IATA AHM 810 / SGHA",
            system="OpsBridge OCC",
            sections=(
                "Station Profile",
                "Scope of Handling",
                "Staffing and Shift Pattern",
                "Arrival Procedure",
                "Departure Procedure",
                "Irregular Operations",
                "Local Regulatory Requirements",
            ),
        ),
        DocType(
            key="mel",
            name="Minimum Equipment List Item",
            abbrev="MEL",
            id_grammar="MEL",
            weight=1.3,
            authority="14 CFR Part 121.628",
            system="OpsBridge OCC",
            sections=(
                "ATA Reference",
                "Item and Installed Quantity",
                "Number Required for Dispatch",
                "Repair Interval Category",
                "Operational Procedure (O)",
                "Maintenance Procedure (M)",
                "Placarding",
            ),
        ),
        DocType(
            key="release",
            name="Dispatch Release",
            abbrev="DR",
            id_grammar="DR",
            weight=1.6,
            authority="14 CFR Part 121.687",
            system="OpsBridge OCC",
            sections=(
                "Flight Identification",
                "Aircraft and Configuration",
                "Route and Alternates",
                "Fuel Plan",
                "Weather and NOTAMs",
                "Open MEL and CDL Items",
                "Weight and Balance Summary",
                "Dispatcher Release",
            ),
        ),
        DocType(
            key="irops",
            name="Irregular Operations Recovery Plan",
            abbrev="IROPS",
            id_grammar="IRP",
            weight=1.0,
            authority="14 CFR Part 259 / SMS",
            system="OpsBridge OCC",
            sections=(
                "Trigger Conditions",
                "Command and Control",
                "Passenger Reaccommodation",
                "Crew Legality Management",
                "Aircraft Recovery Sequencing",
                "Station Communication",
                "Post-Event Review",
            ),
        ),
        DocType(
            key="fdp",
            name="Flight Duty Period Compliance Note",
            abbrev="FDP",
            id_grammar="FTL",
            weight=0.9,
            authority="14 CFR Part 117",
            system="CrewLink",
            sections=(
                "Applicable Limitation",
                "Pairing Construction",
                "Augmentation and Rest",
                "Cumulative Limits",
                "Fatigue Risk Assessment",
                "Exception Handling",
            ),
        ),
        DocType(
            key="safety",
            name="Safety Investigation Report",
            abbrev="SIR",
            id_grammar="SIR",
            weight=1.0,
            authority="SMS / 14 CFR Part 5",
            system="SafetyNet SMS",
            sections=(
                "Event Summary",
                "Sequence of Events",
                "Contributing Factors",
                "Risk Assessment",
                "Corrective Actions",
                "Effectiveness Review",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="ata",
            name="ATA iSpec 2200 chapter",
            authority="Airlines for America",
            fmt="CC-SS",
            codes=ATA_CHAPTERS,
        ),
        CodeSystem(
            key="delay",
            name="IATA delay code",
            authority="IATA AHM 730/731",
            fmt="two-digit numeric",
            codes=IATA_DELAY_CODES,
        ),
        CodeSystem(
            key="oooi",
            name="OOOI movement milestone",
            authority="ACARS / A-CDM",
            fmt="four events per leg",
            codes=(
                ("OUT", "Gate departure, parking brake released"),
                ("OFF", "Wheels off, takeoff"),
                ("ON", "Wheels on, landing"),
                ("IN", "Gate arrival, parking brake set"),
            ),
        ),
    ),
    workflows=(
        Workflow(
            key="flight",
            name="Flight lifecycle",
            states=("Scheduled", "Planned", "Released", "Boarding", "Out",
                    "Off", "On", "In", "Closed"),
            terminal=("Closed",),
        ),
        Workflow(
            key="mel_defer",
            name="MEL deferral",
            states=("Defect reported", "MEL applied", "Deferred",
                    "Repair interval expiring", "Rectified"),
            terminal=("Rectified",),
        ),
    ),
    lexicon=(
        "OOOI", "ETOPS", "MEL", "CDL", "NOTOC", "NOTAM", "METAR", "TAF",
        "PIC", "SIC", "FDP", "bidline", "pairing", "deadhead", "IROPS",
        "MOC", "OCC", "block time", "tail swap", "ferry flight", "TOBT",
        "turnaround", "station", "A-CDM", "FOQA", "ASAP",
    ),
    subjects=(
        "gate turnaround", "de-icing", "pushback", "cabin readiness",
        "crew legality", "fuel uplift", "load planning", "baggage transfer",
        "diversion recovery", "aircraft swap", "curfew management",
        "wheelchair assistance", "dangerous goods acceptance",
        "ramp safety", "jet bridge operation", "catering uplift",
        "potable water servicing", "cargo build-up", "weight and balance",
        "irregular operations command",
    ),
    sites=(
        "ZZZZ Hub North", "ZZZZ Hub Coastal", "Station Alpha",
        "Station Meridian", "Station Kestrel", "Line Station Vega",
        "Maintenance Base North", "Crew Base Coastal",
    ),
    ontology=(
        ("Flight", "OPERATED_BY", "Aircraft"),
        ("Flight", "DEPARTS_FROM", "Station"),
        ("Flight", "RELEASED_BY", "DispatchRelease"),
        ("Flight", "DELAYED_BY", "DelayCode"),
        ("Aircraft", "HAS_OPEN_ITEM", "MELItem"),
        ("MELItem", "CLASSIFIED_UNDER", "ATAChapter"),
        ("Procedure", "OWNED_BY", "Unit"),
        ("Procedure", "APPLIES_AT", "Station"),
        ("SafetyReport", "IDENTIFIES", "ContributingFactor"),
        ("CrewPairing", "CONSTRAINED_BY", "FDPLimit"),
    ),
    questions=(
        "What is the repair interval for a Category B MEL item and who approves an extension?",
        "Which delay codes are assigned when de-icing pushes a departure past its slot?",
        "How does crew legality get re-checked during an IROPS recovery?",
        "What has to be on a dispatch release before the aircraft can push back?",
        "Which stations handle dangerous goods acceptance without a third-party agent?",
    ),
)


AEROTECH = Pack(
    slug="q-aerotech",
    spine="component",
    tenant="Q-Aerotech",
    industry="Aerospace MRO — Part-145",
    tagline="Base and line maintenance · CAMO · component shops",
    accent="#00A3F4",
    units=(
        "Base Maintenance",
        "Line Maintenance",
        "Component Shops",
        "Engineering",
        "Planning and Production Control",
        "Quality Assurance",
        "Technical Records",
        "CAMO",
        "Stores and Material",
        "Tooling and Calibration",
        "Non-Destructive Testing",
    ),
    roles=(
        "Accountable Manager",
        "Quality Manager",
        "Continuing Airworthiness Manager",
        "Base Maintenance Manager",
        "Certifying Staff (B1)",
        "Certifying Staff (B2)",
        "Design Engineer, Repairs",
        "Planning Engineer",
        "Airworthiness Review Staff",
        "NDT Level 3",
    ),
    systems=(
        "Keelson MRO",
        "Keelson Technical Records",
        "ToolTrace Calibration",
        "PartsLedger Stores",
    ),
    doc_types=(
        DocType(
            key="ad",
            name="Airworthiness Directive Compliance Record",
            abbrev="ADCR",
            id_grammar="ADCR",
            weight=1.4,
            authority="14 CFR Part 39 / EU 748/2012",
            system="Keelson Technical Records",
            sections=(
                "Directive Reference",
                "Applicability Assessment",
                "Compliance Method",
                "Accomplishment Instructions",
                "Recurring Inspection Interval",
                "Compliance Statement",
                "Records Entry",
            ),
        ),
        DocType(
            key="eo",
            name="Engineering Order",
            abbrev="EO",
            id_grammar="EO",
            weight=1.5,
            authority="Part-145 / Part-21 design data",
            system="Keelson MRO",
            sections=(
                "Reason for Issue",
                "Effectivity",
                "Approved Design Data",
                "Accomplishment Instructions",
                "Parts and Materials",
                "Weight and Balance Effect",
                "Sign-Off Requirements",
            ),
        ),
        DocType(
            key="taskcard",
            name="Maintenance Task Card",
            abbrev="TC",
            id_grammar="TC",
            weight=1.8,
            authority="MPD / AMM",
            system="Keelson MRO",
            sections=(
                "Task Reference and ATA",
                "Applicability and Effectivity",
                "Zone and Access",
                "Manual References",
                "Tools and Consumables",
                "Warnings and Cautions",
                "Task Steps",
                "Inspection and Sign-Off",
            ),
        ),
        DocType(
            key="nrc",
            name="Non-Routine Card",
            abbrev="NRC",
            id_grammar="NRC",
            weight=1.6,
            authority="Part-145.A.50",
            system="Keelson MRO",
            sections=(
                "Finding Description",
                "Originating Task",
                "Damage Assessment",
                "Disposition",
                "Repair Scheme Reference",
                "Rectification Steps",
                "Certification",
            ),
        ),
        DocType(
            key="sb",
            name="Service Bulletin Evaluation",
            abbrev="SBE",
            id_grammar="SBE",
            weight=1.1,
            authority="OEM SB / Part-M.A.301",
            system="Keelson Technical Records",
            sections=(
                "Bulletin Reference",
                "Category and Compliance Status",
                "Fleet Applicability",
                "Cost and Downtime Assessment",
                "Embodiment Plan",
                "Decision and Rationale",
            ),
        ),
        DocType(
            key="crs",
            name="Certificate of Release to Service",
            abbrev="CRS",
            id_grammar="CRS",
            weight=1.2,
            authority="Part-145.A.50(d)",
            system="Keelson MRO",
            sections=(
                "Work Package Reference",
                "Maintenance Performed",
                "Deferred Items",
                "Limitations",
                "Certifying Statement",
                "Authorisation",
            ),
        ),
        DocType(
            key="capability",
            name="Capability List Entry",
            abbrev="CAP",
            id_grammar="CAP",
            weight=0.8,
            authority="Part-145.A.42",
            system="Keelson MRO",
            sections=(
                "Component and Part Number",
                "Rating and Scope",
                "Technical Data Held",
                "Tooling and Test Equipment",
                "Personnel Authorisation",
                "Facility Requirements",
            ),
        ),
        DocType(
            key="llp",
            name="Life-Limited Part Traceability Record",
            abbrev="LLP",
            id_grammar="LLP",
            weight=1.0,
            authority="Part-M.A.305 / back-to-birth",
            system="Keelson Technical Records",
            sections=(
                "Part Identity",
                "Life Limit and Basis",
                "Accumulated Cycles and Hours",
                "Installation History",
                "Back-to-Birth Evidence",
                "Remaining Life Assessment",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="ata",
            name="ATA iSpec 2200 chapter",
            authority="Airlines for America",
            fmt="CC-SS",
            codes=ATA_CHAPTERS,
        ),
        CodeSystem(
            key="check",
            name="Maintenance check level",
            authority="MPD",
            fmt="letter check",
            codes=(
                ("A", "Line check, approx. 600–900 flight hours"),
                ("C", "Base check, approx. 20–24 months"),
                ("D", "Heavy structural check, approx. 6–10 years"),
                ("IL", "Intermediate layover"),
            ),
        ),
        CodeSystem(
            key="disposition",
            name="Component disposition",
            authority="Part-145 shop practice",
            fmt="controlled state",
            codes=(
                ("SVC", "Serviceable, released on Form 1"),
                ("UNS", "Unserviceable, awaiting shop"),
                ("BER", "Beyond economic repair"),
                ("SCP", "Scrapped, mutilated and recorded"),
                ("QTN", "Quarantined pending investigation"),
            ),
        ),
    ),
    workflows=(
        Workflow(
            key="workorder",
            name="Work order",
            states=("Open", "In work", "Awaiting parts", "Inspection",
                    "Released to service", "Closed"),
            terminal=("Closed",),
        ),
        Workflow(
            key="ad_compliance",
            name="AD compliance",
            states=("Issued", "Applicability assessed", "EO raised",
                    "Planned", "Accomplished", "Recorded"),
            terminal=("Recorded",),
        ),
    ),
    lexicon=(
        "AOG", "RTS", "CRS", "EO", "NRC", "LLP", "TSN", "TSO", "CSN", "CSO",
        "back-to-birth", "buy-back", "hard time", "on-condition",
        "condition monitoring", "dual release", "check package", "robbing",
        "effectivity", "Form 1", "8130-3", "CAMO", "MPD", "AMM", "SRM", "IPC",
    ),
    subjects=(
        "wing spar corrosion", "landing gear overhaul", "APU replacement",
        "cabin reconfiguration", "fuel tank inerting", "cargo liner repair",
        "engine borescope inspection", "flight control rigging",
        "pitot-static certification", "emergency lighting test",
        "composite delamination", "fastener hole oversizing",
        "hydraulic actuator leak", "avionics software load",
        "oxygen bottle hydrostatic test", "de-icing boot replacement",
        "windshield heat controller", "thrust reverser actuation",
        "nacelle acoustic panel", "structural repair scheme",
    ),
    sites=(
        "Hangar 4 — Base North", "Hangar 7 — Wide-body Bay",
        "Component Shop — Hydraulics", "Component Shop — Avionics",
        "NDT Cell 2", "Paint Bay", "Line Station Vega", "Engine Test Cell",
    ),
    ontology=(
        ("Aircraft", "HAS_COMPONENT", "Component"),
        ("Component", "SUBJECT_TO", "AirworthinessDirective"),
        ("WorkOrder", "CONTAINS", "TaskCard"),
        ("TaskCard", "CLASSIFIED_UNDER", "ATAChapter"),
        ("TaskCard", "RAISED", "NonRoutineCard"),
        ("NonRoutineCard", "RESOLVED_BY", "EngineeringOrder"),
        ("EngineeringOrder", "APPROVED_BY", "Role"),
        ("Component", "TRACKED_BY", "LifeLimitRecord"),
        ("ServiceBulletin", "EMBODIED_BY", "EngineeringOrder"),
        ("WorkOrder", "RELEASED_BY", "CertificateOfRelease"),
    ),
    questions=(
        "Which Airworthiness Directives are open against the wing structure and what are their recurring intervals?",
        "How does a non-routine finding become an approved repair scheme?",
        "What evidence is required for back-to-birth traceability on a life-limited part?",
        "Who can sign a Certificate of Release to Service after a C-check?",
        "Which service bulletins were deferred and on what cost rationale?",
    ),
)
