"""Clinical and life-sciences packs: provider, payer, pharma, device."""

from .base import CodeSystem, DocType, Pack, Workflow

# ---------------------------------------------------------------------------
# Shared clinical vocabularies.
#
# Code descriptions here are limited to publicly documented category labels and
# formats. Licensed terminologies (CPT, SNOMED CT) are referenced by format and
# authority only — the generator never embeds their proprietary descriptors.
# ---------------------------------------------------------------------------

ICD10_SAMPLE = (
    ("E11.9", "Type 2 diabetes mellitus without complications"),
    ("I10", "Essential (primary) hypertension"),
    ("J44.1", "Chronic obstructive pulmonary disease with exacerbation"),
    ("N18.3", "Chronic kidney disease, stage 3"),
    ("I50.32", "Chronic diastolic (congestive) heart failure"),
    ("J18.9", "Pneumonia, unspecified organism"),
    ("A41.9", "Sepsis, unspecified organism"),
    ("K21.9", "Gastro-oesophageal reflux disease without oesophagitis"),
    ("M54.5", "Low back pain"),
    ("R07.9", "Chest pain, unspecified"),
    ("Z79.4", "Long term (current) use of insulin"),
    ("E78.5", "Hyperlipidaemia, unspecified"),
)

LOINC_SAMPLE = (
    ("2160-0", "Creatinine [Mass/volume] in Serum or Plasma"),
    ("718-7", "Haemoglobin [Mass/volume] in Blood"),
    ("4548-4", "Haemoglobin A1c/Haemoglobin.total in Blood"),
    ("2951-2", "Sodium [Moles/volume] in Serum or Plasma"),
    ("6690-2", "Leukocytes [#/volume] in Blood"),
    ("1975-2", "Bilirubin.total [Mass/volume] in Serum or Plasma"),
    ("2093-3", "Cholesterol [Mass/volume] in Serum or Plasma"),
    ("33914-3", "Glomerular filtration rate/1.73 sq M.predicted"),
)

FHIR_RESOURCES = (
    ("Patient", "Demographics and administrative identity"),
    ("Encounter", "An interaction during which services are provided"),
    ("Observation", "Measurements and simple assertions"),
    ("Condition", "Clinical condition, problem or diagnosis"),
    ("MedicationRequest", "Ordering of medication"),
    ("MedicationAdministration", "Medication actually given to a patient"),
    ("DiagnosticReport", "Findings and interpretation of diagnostic tests"),
    ("DocumentReference", "Reference to a clinical document"),
    ("Procedure", "An action performed on a patient"),
    ("AllergyIntolerance", "Risk of harmful reaction to a substance"),
    ("ServiceRequest", "Request for a service to be performed"),
    ("CarePlan", "Intended plan of care for a patient"),
    ("Coverage", "Insurance or medical plan coverage"),
)

HL7V2_MESSAGES = (
    ("ADT^A01", "Admit / visit notification"),
    ("ADT^A03", "Discharge / end visit"),
    ("ADT^A08", "Update patient information"),
    ("ORM^O01", "General order message"),
    ("ORU^R01", "Unsolicited observation result"),
    ("MDM^T02", "Original document notification and content"),
    ("SIU^S12", "Notification of new appointment booking"),
)


HEALTH = Pack(
    slug="q-health",
    spine="pathway",
    tenant="Q-Health",
    industry="Integrated Healthcare Delivery",
    tagline="4 acute sites · 1,180 beds · Level II trauma",
    accent="#31C4B0",
    units=(
        "Emergency Department",
        "Intensive Care",
        "Perioperative Services",
        "Medical-Surgical Nursing",
        "Laboratory Services",
        "Diagnostic Imaging",
        "Pharmacy Services",
        "Case Management",
        "Health Information Management",
        "Quality and Patient Safety",
        "Infection Prevention",
        "Revenue Cycle",
    ),
    roles=(
        "Chief Medical Officer",
        "Chief Nursing Officer",
        "Attending Physician",
        "Hospitalist",
        "Charge Nurse",
        "Clinical Pharmacist",
        "Nurse Practitioner",
        "Case Manager",
        "HIM Director",
        "Infection Preventionist",
    ),
    systems=(
        "Cedar Chart EHR",
        "Cedar Lab LIS",
        "Cedar Imaging PACS",
        "Cedar Rx Pharmacy",
        "SafeReport Event System",
    ),
    doc_types=(
        DocType(
            key="pathway",
            name="Clinical Care Pathway",
            abbrev="CCP",
            id_grammar="CCP",
            weight=1.4,
            authority="Joint Commission / CMS CoP",
            system="Cedar Chart EHR",
            sections=(
                "Condition and Inclusion Criteria",
                "Exclusion Criteria",
                "Day-by-Day Interventions",
                "Order Set Linkage",
                "Expected Length of Stay",
                "Variance Documentation",
                "Discharge Criteria",
            ),
        ),
        DocType(
            key="orderset",
            name="Order Set Specification",
            abbrev="OS",
            id_grammar="OS",
            weight=1.5,
            authority="CPOE governance",
            system="Cedar Chart EHR",
            sections=(
                "Clinical Indication",
                "Included Orders",
                "Default Selections",
                "Dose Range Checking",
                "Allergy and Interaction Rules",
                "Evidence Basis",
                "Review Cycle",
            ),
        ),
        DocType(
            key="mar",
            name="Medication Administration Policy",
            abbrev="MAR",
            id_grammar="MAR",
            weight=1.3,
            authority="CMS CoP §482.23 / NPSG",
            system="Cedar Rx Pharmacy",
            sections=(
                "Scope and Applicability",
                "Rights of Administration",
                "Barcode Verification",
                "High-Alert Medications",
                "Documentation in the eMAR",
                "Held, Refused and Missed Doses",
                "Discrepancy Reporting",
            ),
        ),
        DocType(
            key="interop",
            name="Interoperability Interface Specification",
            abbrev="IFC",
            id_grammar="IFC",
            weight=1.2,
            authority="HL7 v2.5.1 / FHIR R4 US Core",
            system="Cedar Chart EHR",
            sections=(
                "Interface Purpose",
                "Message or Resource Profile",
                "Trigger Events",
                "Segment and Field Mapping",
                "Terminology Bindings",
                "Error Handling and Acknowledgement",
                "Testing and Validation",
            ),
        ),
        DocType(
            key="policy",
            name="Clinical Policy and Procedure",
            abbrev="CPP",
            id_grammar="CPP",
            weight=1.6,
            authority="Joint Commission standards",
            system="Cedar Chart EHR",
            sections=(
                "Policy Statement",
                "Scope",
                "Definitions",
                "Procedure",
                "Documentation Requirements",
                "Competency and Training",
                "Monitoring and Compliance",
            ),
        ),
        DocType(
            key="event",
            name="Patient Safety Event Review",
            abbrev="PSE",
            id_grammar="PSE",
            weight=1.1,
            authority="Patient Safety Organisation framework",
            system="SafeReport Event System",
            sections=(
                "Event Classification",
                "Narrative Summary",
                "Contributing Factors",
                "Harm Score",
                "Immediate Actions",
                "Corrective Action Plan",
                "Sustained Improvement Check",
            ),
        ),
        DocType(
            key="coding",
            name="Clinical Documentation and Coding Guidance",
            abbrev="CDI",
            id_grammar="CDI",
            weight=1.0,
            authority="ICD-10-CM Official Guidelines",
            system="Cedar Chart EHR",
            sections=(
                "Documentation Requirement",
                "Code Assignment Rules",
                "Present on Admission Determination",
                "Query Guidance",
                "DRG Impact",
                "Audit Findings",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="icd10",
            name="ICD-10-CM",
            authority="CDC / NCHS",
            fmt="3–7 alphanumeric, decimal after the third character",
            codes=ICD10_SAMPLE,
        ),
        CodeSystem(
            key="loinc",
            name="LOINC",
            authority="Regenstrief Institute",
            fmt="NNNNN-N",
            codes=LOINC_SAMPLE,
        ),
        CodeSystem(
            key="fhir",
            name="HL7 FHIR R4 resource",
            authority="HL7 International",
            fmt="CamelCase resource type",
            codes=FHIR_RESOURCES,
        ),
        CodeSystem(
            key="hl7v2",
            name="HL7 v2 message type",
            authority="HL7 International",
            fmt="TYPE^EVENT",
            codes=HL7V2_MESSAGES,
        ),
    ),
    workflows=(
        Workflow(
            key="encounter",
            name="Encounter status",
            states=("Planned", "Arrived", "In progress", "Finished", "Cancelled"),
            terminal=("Finished", "Cancelled"),
        ),
        Workflow(
            key="medication",
            name="Medication administration",
            states=("Ordered", "Pharmacy verified", "Dispensed",
                    "Administered", "Held", "Refused", "Missed"),
            terminal=("Administered", "Refused", "Missed"),
        ),
    ),
    lexicon=(
        "MAR", "eMAR", "CPOE", "SBAR", "H&P", "ROS", "NPO", "PRN", "STAT",
        "DRG", "POA", "LOS", "order set", "hard stop", "BPA", "code status",
        "US Core", "USCDI", "ADT", "ORU", "C-CDA", "MRN", "accession",
    ),
    subjects=(
        "sepsis recognition", "stroke activation", "insulin titration",
        "anticoagulation reversal", "central line insertion",
        "ventilator weaning", "discharge medication reconciliation",
        "pressure injury prevention", "falls risk assessment",
        "blood product administration", "antimicrobial stewardship",
        "restraint use", "hand-off communication", "specimen labelling",
        "contrast allergy screening", "opioid monitoring",
        "delirium screening", "venous thromboembolism prophylaxis",
        "rapid response activation", "critical value notification",
    ),
    sites=(
        "Cedarline Central", "Cedarline North Campus",
        "Cedarline Riverside", "Cedarline Ambulatory Centre",
        "Unit 4 West", "Unit 6 East", "Cardiac ICU", "Emergency Department",
    ),
    ontology=(
        ("Patient", "HAS_ENCOUNTER", "Encounter"),
        ("Encounter", "HAS_DIAGNOSIS", "Condition"),
        ("Encounter", "HAS_ORDER", "ServiceRequest"),
        ("ServiceRequest", "RESULTS_IN", "Observation"),
        ("Observation", "CODED_BY", "LOINCCode"),
        ("Condition", "CODED_BY", "ICD10Code"),
        ("CarePathway", "REFERENCES", "OrderSet"),
        ("Policy", "OWNED_BY", "Unit"),
        ("SafetyEvent", "IDENTIFIES", "ContributingFactor"),
        ("Interface", "EXCHANGES", "FHIRResource"),
    ),
    questions=(
        "Which order sets are linked to the sepsis pathway and what triggers them?",
        "How are high-alert medications verified before administration?",
        "What terminology bindings does the results interface use for laboratory observations?",
        "Which contributing factors appear most often in medication safety events?",
        "When must present-on-admission be determined and who decides it?",
    ),
)


CLAIMS = Pack(
    slug="q-assure-claims",
    spine="policy",
    tenant="Q-Assure Claims",
    industry="Health Plan Operations and Claims",
    tagline="2.1M members · commercial, Medicare Advantage, ASO",
    accent="#6D5BD0",
    units=(
        "Claims Operations",
        "Utilization Management",
        "Prior Authorization",
        "Provider Network",
        "Credentialing",
        "Member Services",
        "Appeals and Grievances",
        "Medical Policy",
        "Payment Integrity",
        "Risk Adjustment",
        "Quality and Stars",
        "Enrolment",
    ),
    roles=(
        "Vice President, Claims Operations",
        "Medical Director",
        "Claims Examiner",
        "Utilization Review Nurse",
        "Prior Authorization Coordinator",
        "Provider Relations Representative",
        "Credentialing Specialist",
        "Appeals Coordinator",
        "Risk Adjustment Coder",
        "Payment Integrity Analyst",
    ),
    systems=(
        "Provident Core Claims",
        "AuthBridge UM",
        "NetworkLedger",
        "AppealTrack",
    ),
    doc_types=(
        DocType(
            key="medpolicy",
            name="Medical Coverage Policy",
            abbrev="MCP",
            id_grammar="MCP",
            weight=1.5,
            authority="Plan medical policy committee",
            system="Provident Core Claims",
            sections=(
                "Policy Statement",
                "Coverage Criteria",
                "Medical Necessity Requirements",
                "Exclusions and Limitations",
                "Applicable Codes",
                "Evidence Review",
                "Review and Revision History",
            ),
        ),
        DocType(
            key="edi",
            name="EDI Companion Guide",
            abbrev="EDI",
            id_grammar="EDI",
            weight=1.2,
            authority="X12 005010 TR3",
            system="Provident Core Claims",
            sections=(
                "Transaction Scope",
                "Connectivity and Envelope",
                "Loop and Segment Requirements",
                "Situational Data Elements",
                "Acknowledgement Model",
                "Rejection Handling",
                "Trading Partner Testing",
            ),
        ),
        DocType(
            key="denial",
            name="Denial Reason Handling Standard",
            abbrev="DRS",
            id_grammar="DRS",
            weight=1.4,
            authority="CARC / RARC code sets",
            system="Provident Core Claims",
            sections=(
                "Applicable Adjustment Codes",
                "Root Cause Categories",
                "Examiner Decision Rules",
                "Provider Communication",
                "Reprocessing Criteria",
                "Appeal Rights",
            ),
        ),
        DocType(
            key="priorauth",
            name="Prior Authorization Requirement",
            abbrev="PA",
            id_grammar="PA",
            weight=1.3,
            authority="X12 278 / plan UM policy",
            system="AuthBridge UM",
            sections=(
                "Services Requiring Authorization",
                "Clinical Criteria Applied",
                "Submission Channels",
                "Turnaround Standards",
                "Adverse Determination Process",
                "Peer-to-Peer Review",
            ),
        ),
        DocType(
            key="appeal",
            name="Appeals and Grievances Procedure",
            abbrev="AGP",
            id_grammar="AGP",
            weight=1.1,
            authority="CMS / state DOI requirements",
            system="AppealTrack",
            sections=(
                "Appeal Levels",
                "Filing Windows",
                "Acknowledgement Requirements",
                "Clinical Review Assignment",
                "Independent Review",
                "Resolution and Notification",
            ),
        ),
        DocType(
            key="credential",
            name="Provider Credentialing Standard",
            abbrev="CRD",
            id_grammar="CRD",
            weight=1.0,
            authority="NCQA credentialing standards",
            system="NetworkLedger",
            sections=(
                "Application Requirements",
                "Primary Source Verification",
                "Committee Review",
                "Recredentialing Cycle",
                "Adverse Action Handling",
                "Delegated Arrangements",
            ),
        ),
        DocType(
            key="integrity",
            name="Payment Integrity Edit Specification",
            abbrev="PIE",
            id_grammar="PIE",
            weight=1.2,
            authority="Plan payment policy",
            system="Provident Core Claims",
            sections=(
                "Edit Intent",
                "Trigger Logic",
                "Code Pairs and Modifiers",
                "Provider Impact Assessment",
                "Override Criteria",
                "Monitoring Metrics",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="x12",
            name="X12 HIPAA transaction set",
            authority="ASC X12N",
            fmt="three-digit set with TR3 guide",
            codes=(
                ("270", "Eligibility, coverage or benefit inquiry"),
                ("271", "Eligibility, coverage or benefit response"),
                ("276", "Health care claim status request"),
                ("277", "Health care claim status response"),
                ("278", "Health care services review — authorization"),
                ("834", "Benefit enrolment and maintenance"),
                ("835", "Health care claim payment / advice"),
                ("837P", "Health care claim — professional"),
                ("837I", "Health care claim — institutional"),
                ("999", "Implementation acknowledgement"),
            ),
        ),
        CodeSystem(
            key="carc",
            name="Claim Adjustment Reason Code",
            authority="X12 / WPC code list",
            fmt="numeric with CO/PR/OA/PI group code",
            codes=(
                ("1", "Deductible amount"),
                ("2", "Coinsurance amount"),
                ("3", "Co-payment amount"),
                ("16", "Claim or service lacks information needed for adjudication"),
                ("18", "Exact duplicate claim or service"),
                ("22", "Care may be covered by another payer per coordination of benefits"),
                ("45", "Charge exceeds fee schedule or contracted amount"),
                ("50", "Non-covered — not deemed a medical necessity"),
                ("96", "Non-covered charges"),
                ("97", "Benefit included in the payment for another service"),
                ("197", "Precertification or authorization absent"),
            ),
        ),
        CodeSystem(
            key="pos",
            name="Place of Service code",
            authority="CMS",
            fmt="two-digit numeric",
            codes=(
                ("11", "Office"),
                ("19", "Off-campus outpatient hospital"),
                ("21", "Inpatient hospital"),
                ("22", "On-campus outpatient hospital"),
                ("23", "Emergency room — hospital"),
                ("24", "Ambulatory surgical centre"),
                ("31", "Skilled nursing facility"),
                ("81", "Independent laboratory"),
            ),
        ),
    ),
    workflows=(
        Workflow(
            key="claim",
            name="Claim adjudication",
            states=("Received", "Accepted", "Pended", "Adjudicated",
                    "Paid", "Denied", "Appealed", "Reprocessed"),
            terminal=("Paid", "Denied"),
        ),
        Workflow(
            key="auth",
            name="Prior authorization",
            states=("Requested", "Clinical review", "Approved",
                    "Partially approved", "Denied", "Appealed"),
            terminal=("Approved", "Denied"),
        ),
    ),
    lexicon=(
        "ICN", "COB", "ERA", "EFT", "clean claim", "timely filing",
        "pend", "precert", "medical necessity", "downcoding", "recoup",
        "HCC", "RAF", "PMPM", "MLR", "CARC", "RARC", "TR3", "837P", "835",
    ),
    subjects=(
        "advanced imaging authorization", "durable medical equipment",
        "out-of-network emergency care", "coordination of benefits",
        "duplicate claim detection", "modifier 25 review",
        "inpatient level of care", "observation status",
        "specialty pharmacy benefit", "behavioural health parity",
        "skilled nursing transfer", "home health episode",
        "clinical trial routine costs", "genetic testing coverage",
        "physical therapy visit limits", "telehealth place of service",
        "readmission review", "high-cost claimant review",
        "provider overpayment recovery", "credentialing lapse",
    ),
    sites=(
        "Claims Centre East", "Claims Centre Central",
        "Clinical Review Unit", "Appeals Unit", "Payment Integrity Lab",
    ),
    ontology=(
        ("Claim", "SUBMITTED_BY", "Provider"),
        ("Claim", "ADJUDICATED_TO", "RemittanceAdvice"),
        ("RemittanceAdvice", "HAS_ADJUSTMENT", "CARCCode"),
        ("Claim", "GOVERNED_BY", "MedicalPolicy"),
        ("MedicalPolicy", "REQUIRES", "PriorAuthorization"),
        ("Provider", "CREDENTIALED_UNDER", "CredentialingStandard"),
        ("Denial", "APPEALED_THROUGH", "AppealLevel"),
        ("EDIGuide", "IMPLEMENTS", "X12TransactionSet"),
        ("PaymentEdit", "TARGETS", "CodePair"),
    ),
    questions=(
        "Which CARC codes drive the highest denial volume and what is the reprocessing rule for each?",
        "What clinical criteria apply to advanced imaging prior authorization?",
        "How long does a provider have to file a first-level appeal?",
        "Which loops in the 837P carry coordination-of-benefits data?",
        "What triggers a payment integrity edit on modifier 25?",
    ),
)


PHARMA = Pack(
    slug="q-pharma",
    spine="product",
    tenant="Q-Pharma",
    industry="Pharmaceutical Development and Manufacturing",
    tagline="Clinical stage to commercial · GMP sterile fill-finish",
    accent="#16A34A",
    units=(
        "Clinical Operations",
        "Regulatory Affairs",
        "Pharmacovigilance",
        "Quality Assurance",
        "Quality Control",
        "Manufacturing",
        "Manufacturing Science and Technology",
        "Validation",
        "Chemistry, Manufacturing and Controls",
        "Medical Writing",
        "Biostatistics and Data Management",
    ),
    roles=(
        "Qualified Person",
        "Head of Quality Assurance",
        "QC Laboratory Manager",
        "Production Manager",
        "Regulatory Affairs Director",
        "Clinical Research Associate",
        "Principal Investigator",
        "Drug Safety Physician",
        "Validation Engineer",
        "Medical Writer",
    ),
    systems=(
        "Verenda Vault QMS",
        "Verenda eTMF",
        "LabLedger LIMS",
        "BatchTrace MES",
        "SafetyGate PV",
    ),
    doc_types=(
        DocType(
            key="protocol",
            name="Clinical Trial Protocol",
            abbrev="PROT",
            id_grammar="PROT",
            weight=1.2,
            authority="ICH E6(R2) GCP",
            system="Verenda eTMF",
            sections=(
                "Background and Rationale",
                "Objectives and Endpoints",
                "Study Design",
                "Eligibility Criteria",
                "Treatment and Administration",
                "Assessments and Schedule",
                "Statistical Considerations",
                "Safety Reporting",
                "Ethics and Regulatory",
            ),
        ),
        DocType(
            key="deviation",
            name="Deviation Investigation Report",
            abbrev="DEV",
            id_grammar="DEV",
            weight=1.6,
            authority="21 CFR 211.192 / EU GMP Ch.1",
            system="Verenda Vault QMS",
            sections=(
                "Deviation Description",
                "Immediate Containment",
                "Batch and Product Impact",
                "Investigation and Root Cause",
                "Risk Assessment",
                "CAPA Reference",
                "Disposition Decision",
            ),
        ),
        DocType(
            key="capa",
            name="Corrective and Preventive Action Record",
            abbrev="CAPA",
            id_grammar="CAPA",
            weight=1.4,
            authority="ICH Q10",
            system="Verenda Vault QMS",
            sections=(
                "Problem Statement",
                "Source and Trigger",
                "Root Cause Analysis",
                "Corrective Actions",
                "Preventive Actions",
                "Implementation Plan",
                "Effectiveness Check",
            ),
        ),
        DocType(
            key="bmr",
            name="Batch Manufacturing Record Instruction",
            abbrev="BMR",
            id_grammar="BMR",
            weight=1.3,
            authority="21 CFR 211.186 / EU GMP Annex 1",
            system="BatchTrace MES",
            sections=(
                "Product and Batch Identity",
                "Bill of Materials",
                "Equipment and Line Clearance",
                "Process Steps and Parameters",
                "In-Process Controls",
                "Yield Reconciliation",
                "Batch Review and Release",
            ),
        ),
        DocType(
            key="oos",
            name="Out-of-Specification Investigation",
            abbrev="OOS",
            id_grammar="OOS",
            weight=1.2,
            authority="FDA OOS guidance / 21 CFR 211.192",
            system="LabLedger LIMS",
            sections=(
                "Result and Specification",
                "Phase I Laboratory Investigation",
                "Hypothesis Testing",
                "Phase II Full Investigation",
                "Retest and Resample Justification",
                "Conclusion and Disposition",
            ),
        ),
        DocType(
            key="validation",
            name="Validation Protocol and Report",
            abbrev="VAL",
            id_grammar="VAL",
            weight=1.1,
            authority="ICH Q8/Q9 / Annex 15",
            system="Verenda Vault QMS",
            sections=(
                "Scope and System Description",
                "Acceptance Criteria",
                "Installation Qualification",
                "Operational Qualification",
                "Performance Qualification",
                "Deviations During Execution",
                "Conclusion and Release",
            ),
        ),
        DocType(
            key="csr",
            name="Clinical Study Report Section",
            abbrev="CSR",
            id_grammar="CSR",
            weight=1.0,
            authority="ICH E3",
            system="Verenda eTMF",
            sections=(
                "Synopsis",
                "Investigational Plan",
                "Study Patients",
                "Efficacy Evaluation",
                "Safety Evaluation",
                "Discussion and Conclusions",
            ),
        ),
        DocType(
            key="change",
            name="Change Control Record",
            abbrev="CC",
            id_grammar="CC",
            weight=1.3,
            authority="ICH Q10 / Q12",
            system="Verenda Vault QMS",
            sections=(
                "Change Description",
                "Justification",
                "Impact Assessment",
                "Regulatory Reportability",
                "Implementation Actions",
                "Verification and Closure",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="ectd",
            name="eCTD module",
            authority="ICH M4",
            fmt="Module 1–5",
            codes=(
                ("1", "Regional administrative information"),
                ("2", "Common technical document summaries"),
                ("3", "Quality"),
                ("4", "Non-clinical study reports"),
                ("5", "Clinical study reports"),
            ),
        ),
        CodeSystem(
            key="ich",
            name="ICH guideline",
            authority="International Council for Harmonisation",
            fmt="letter-number",
            codes=(
                ("Q7", "Good manufacturing practice for active substances"),
                ("Q8", "Pharmaceutical development"),
                ("Q9", "Quality risk management"),
                ("Q10", "Pharmaceutical quality system"),
                ("Q12", "Lifecycle management"),
                ("E3", "Structure and content of clinical study reports"),
                ("E6", "Good clinical practice"),
                ("M4", "Common technical document"),
            ),
        ),
        CodeSystem(
            key="cdisc",
            name="CDISC standard",
            authority="CDISC",
            fmt="standard acronym",
            codes=(
                ("SDTM", "Study data tabulation model"),
                ("ADaM", "Analysis data model"),
                ("CDASH", "Clinical data acquisition standards harmonisation"),
                ("Define-XML", "Dataset metadata definition"),
            ),
        ),
    ),
    workflows=(
        Workflow(
            key="batch",
            name="Batch disposition",
            states=("Dispensing", "In process", "In-process control",
                    "QC testing", "QA review", "Released", "Rejected",
                    "Quarantined"),
            terminal=("Released", "Rejected"),
        ),
        Workflow(
            key="deviation",
            name="Deviation lifecycle",
            states=("Initiated", "Under investigation", "Root cause identified",
                    "CAPA assigned", "Effectiveness check", "Closed"),
            terminal=("Closed",),
        ),
    ),
    lexicon=(
        "GMP", "GCP", "GLP", "CAPA", "OOS", "OOT", "deviation",
        "change control", "batch record", "CoA", "IQ", "OQ", "PQ",
        "TMF", "CSR", "IB", "SAE", "ICSR", "ALCOA+", "QP release",
        "eCTD", "SDTM", "ADaM", "MedDRA",
    ),
    subjects=(
        "sterile filling line intervention", "media fill failure",
        "environmental monitoring excursion", "cleaning validation",
        "analytical method transfer", "stability chamber excursion",
        "container closure integrity", "endotoxin limit exceedance",
        "visual inspection reject rate", "lyophilisation cycle deviation",
        "raw material supplier change", "computerised system access review",
        "data integrity audit trail", "temperature excursion in transit",
        "protocol deviation at site", "informed consent version control",
        "serious adverse event reporting", "batch yield shortfall",
        "equipment requalification", "annual product quality review",
    ),
    sites=(
        "Building 3 — Sterile Fill", "Building 5 — API Suite",
        "QC Microbiology Lab", "QC Chemistry Lab",
        "Warehouse Cold Chain", "Clinical Site 014", "Clinical Site 027",
    ),
    ontology=(
        ("Batch", "MANUFACTURED_UNDER", "BatchRecord"),
        ("Batch", "TESTED_BY", "QCMethod"),
        ("Deviation", "AFFECTS", "Batch"),
        ("Deviation", "RESOLVED_BY", "CAPA"),
        ("OOSResult", "TRIGGERS", "Investigation"),
        ("ChangeControl", "IMPACTS", "ValidatedSystem"),
        ("Protocol", "GOVERNS", "ClinicalSite"),
        ("StudyReport", "SUBMITTED_IN", "eCTDModule"),
        ("CAPA", "VERIFIED_BY", "EffectivenessCheck"),
    ),
    questions=(
        "What triggers a Phase II out-of-specification investigation and who authorises retesting?",
        "How is batch impact assessed when a sterile filling deviation is raised?",
        "Which CAPAs remain open past their effectiveness check date?",
        "What change control steps determine regulatory reportability?",
        "How are protocol deviations at clinical sites escalated?",
    ),
)


DEVICELAB = Pack(
    slug="q-devicelab",
    spine="device",
    tenant="Q-DeviceLab",
    industry="Medical Device Design and Manufacture",
    tagline="Class II and III · ISO 13485 · EU MDR",
    accent="#C2740A",
    units=(
        "Design and Development",
        "Systems Engineering",
        "Verification and Validation",
        "Regulatory Affairs",
        "Quality Assurance",
        "Manufacturing Operations",
        "Supplier Quality",
        "Post-Market Surveillance",
        "Complaint Handling",
        "Clinical Affairs",
        "Test Laboratory",
    ),
    roles=(
        "Vice President, Quality and Regulatory",
        "Design Assurance Engineer",
        "Verification Engineer",
        "Regulatory Affairs Specialist",
        "Risk Manager",
        "Complaint Handling Specialist",
        "Supplier Quality Engineer",
        "Clinical Affairs Manager",
        "Management Representative",
        "Software Quality Engineer",
    ),
    systems=(
        "Arclight eQMS",
        "Arclight PLM",
        "ComplaintDesk",
        "TestVault V&V",
    ),
    doc_types=(
        DocType(
            key="dhf",
            name="Design History File Index",
            abbrev="DHF",
            id_grammar="DHF",
            weight=1.1,
            authority="21 CFR 820.30 / QMSR",
            system="Arclight PLM",
            sections=(
                "Device Description and Intended Use",
                "Design and Development Plan",
                "Design Inputs",
                "Design Outputs",
                "Design Review Records",
                "Verification and Validation",
                "Design Transfer",
                "Design Changes",
            ),
        ),
        DocType(
            key="risk",
            name="Risk Management File Section",
            abbrev="RMF",
            id_grammar="RMF",
            weight=1.4,
            authority="ISO 14971:2019",
            system="Arclight eQMS",
            sections=(
                "Intended Use and Reasonably Foreseeable Misuse",
                "Hazard Identification",
                "Risk Estimation",
                "Risk Control Measures",
                "Residual Risk Evaluation",
                "Benefit-Risk Analysis",
                "Production and Post-Production Information",
            ),
        ),
        DocType(
            key="vv",
            name="Verification and Validation Protocol",
            abbrev="VVP",
            id_grammar="VVP",
            weight=1.6,
            authority="21 CFR 820.30(f)(g)",
            system="TestVault V&V",
            sections=(
                "Requirement Under Test",
                "Test Method and Rationale",
                "Acceptance Criteria",
                "Sample Size Justification",
                "Equipment and Calibration",
                "Test Execution Record",
                "Results and Deviations",
                "Conclusion",
            ),
        ),
        DocType(
            key="swlifecycle",
            name="Software Lifecycle Record",
            abbrev="SLC",
            id_grammar="SLC",
            weight=1.2,
            authority="IEC 62304",
            system="Arclight PLM",
            sections=(
                "Software Safety Classification",
                "Software Requirements",
                "Architectural Design",
                "Unit Implementation and Verification",
                "Integration Testing",
                "Software System Testing",
                "Problem Resolution",
                "SOUP Inventory",
            ),
        ),
        DocType(
            key="capa",
            name="Corrective and Preventive Action Record",
            abbrev="CAPA",
            id_grammar="CAPA",
            weight=1.3,
            authority="21 CFR 820.100",
            system="Arclight eQMS",
            sections=(
                "Issue Description",
                "Source",
                "Investigation and Root Cause",
                "Action Plan",
                "Risk File Impact",
                "Implementation",
                "Effectiveness Verification",
            ),
        ),
        DocType(
            key="complaint",
            name="Complaint Investigation Record",
            abbrev="CMP",
            id_grammar="CMP",
            weight=1.5,
            authority="21 CFR 820.198",
            system="ComplaintDesk",
            sections=(
                "Complaint Intake",
                "Device Identification",
                "Reported Event",
                "Investigation Findings",
                "Reportability Decision",
                "Response to Complainant",
                "Trend Linkage",
            ),
        ),
        DocType(
            key="usability",
            name="Usability Engineering Record",
            abbrev="UER",
            id_grammar="UER",
            weight=1.0,
            authority="IEC 62366-1",
            system="Arclight PLM",
            sections=(
                "Use Specification",
                "User Interface Characteristics",
                "Known Use Problems",
                "Use-Related Hazards",
                "Formative Evaluation",
                "Summative Evaluation",
                "Conclusion on Use Safety",
            ),
        ),
        DocType(
            key="cer",
            name="Clinical Evaluation Report Section",
            abbrev="CER",
            id_grammar="CER",
            weight=1.0,
            authority="EU MDR 2017/745 Annex XIV",
            system="Arclight eQMS",
            sections=(
                "Scope of Evaluation",
                "Device Description and Equivalence",
                "Clinical Background and State of the Art",
                "Literature Appraisal",
                "Clinical Data Analysis",
                "Benefit-Risk Conclusion",
                "Post-Market Clinical Follow-Up Plan",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="swclass",
            name="IEC 62304 software safety class",
            authority="IEC",
            fmt="class letter",
            codes=(
                ("A", "No injury or damage to health is possible"),
                ("B", "Non-serious injury is possible"),
                ("C", "Death or serious injury is possible"),
            ),
        ),
        CodeSystem(
            key="riskband",
            name="Risk acceptability band",
            authority="ISO 14971 policy",
            fmt="band label",
            codes=(
                ("Broadly acceptable", "No further risk reduction required"),
                ("ALARP", "Reduce as far as reasonably practicable"),
                ("Intolerable", "Risk control mandatory before release"),
            ),
        ),
        CodeSystem(
            key="pathway",
            name="Regulatory pathway",
            authority="FDA / EU MDR",
            fmt="pathway name",
            codes=(
                ("510(k)", "Premarket notification, substantial equivalence"),
                ("De Novo", "Novel low-to-moderate risk classification"),
                ("PMA", "Premarket approval, Class III"),
                ("MDR Annex IX", "Conformity assessment, quality system and technical file"),
            ),
        ),
    ),
    workflows=(
        Workflow(
            key="design",
            name="Design control",
            states=("Planning", "Inputs", "Outputs", "Review", "Verification",
                    "Validation", "Transfer", "Commercialised"),
            terminal=("Commercialised",),
        ),
        Workflow(
            key="complaint",
            name="Complaint handling",
            states=("Received", "Triaged", "Under investigation",
                    "Reportability decided", "Responded", "Closed"),
            terminal=("Closed",),
        ),
    ),
    lexicon=(
        "DHF", "DMR", "DHR", "design controls", "V&V", "CAPA", "NCR",
        "FMEA", "ALARP", "essential performance", "CER", "PMS", "PMCF",
        "substantial equivalence", "intended use", "SOUP", "UDI",
        "reportable", "summative", "formative",
    ),
    subjects=(
        "alarm audibility", "battery depletion behaviour",
        "single-fault condition", "biocompatibility of patient contact",
        "electromagnetic immunity", "software update integrity",
        "sterile barrier integrity", "shelf-life determination",
        "use error during setup", "cleaning and disinfection validation",
        "wireless coexistence", "cybersecurity threat model",
        "accessory compatibility", "labelling comprehension",
        "packaging drop testing", "supplier change notification",
        "field corrective action", "trend threshold breach",
        "human factors validation", "essential performance under fault",
    ),
    sites=(
        "Design Centre — Building A", "Pilot Line 1",
        "Environmental Test Lab", "EMC Chamber",
        "Sterilisation Partner Site", "Clinical Evaluation Unit",
    ),
    ontology=(
        ("Device", "SPECIFIED_BY", "DesignInput"),
        ("DesignInput", "VERIFIED_BY", "VerificationProtocol"),
        ("Hazard", "MITIGATED_BY", "RiskControl"),
        ("RiskControl", "IMPLEMENTED_IN", "DesignOutput"),
        ("Complaint", "INVESTIGATED_BY", "InvestigationRecord"),
        ("Complaint", "LINKED_TO", "CAPA"),
        ("CAPA", "UPDATES", "RiskFile"),
        ("SoftwareItem", "CLASSIFIED_AS", "SafetyClass"),
        ("Device", "SUBMITTED_VIA", "RegulatoryPathway"),
    ),
    questions=(
        "Which design inputs have no linked verification protocol?",
        "How is reportability decided when a complaint alleges patient harm?",
        "What residual risks were accepted under ALARP and on what benefit basis?",
        "Which software items are Class C and what testing do they require?",
        "How does a supplier change flow into the risk management file?",
    ),
)
