"""Enterprise packs: banking, external audit, cruise, retail, quality engineering."""

from .base import CodeSystem, DocType, Pack, Workflow

BANK = Pack(
    slug="q-bank",
    spine="borrower",
    tenant="Q-Bank",
    industry="Retail and Commercial Banking",
    tagline="$84B assets · 340 branches · commercial lending",
    accent="#1E3A5F",
    units=(
        "Retail Banking",
        "Commercial Banking",
        "Credit Risk",
        "Market Risk",
        "Operational Risk",
        "Treasury and ALM",
        "BSA/AML Compliance",
        "Financial Crimes",
        "Loan Origination",
        "Credit Administration",
        "Internal Audit",
        "Regulatory Reporting",
    ),
    roles=(
        "Chief Risk Officer",
        "Chief Credit Officer",
        "BSA Officer",
        "Head of Compliance",
        "Commercial Relationship Manager",
        "Senior Credit Underwriter",
        "Model Risk Manager",
        "Loan Review Officer",
        "Internal Audit Director",
        "Treasury Analyst",
    ),
    systems=(
        "Ridgeport Core Banking",
        "CreditPath Origination",
        "SentryAML",
        "RiskLedger",
    ),
    doc_types=(
        DocType(
            key="creditpolicy",
            name="Credit Risk Policy",
            abbrev="CRP",
            id_grammar="CRP",
            weight=1.3,
            authority="Board credit committee charter",
            system="RiskLedger",
            sections=(
                "Policy Statement and Risk Appetite",
                "Authority and Delegation",
                "Underwriting Standards",
                "Concentration Limits",
                "Risk Rating Framework",
                "Exception Handling",
                "Monitoring and Reporting",
            ),
        ),
        DocType(
            key="creditmemo",
            name="Credit Approval Memorandum",
            abbrev="CAM",
            id_grammar="CAM",
            weight=1.6,
            authority="Credit policy CRP-01",
            system="CreditPath Origination",
            sections=(
                "Borrower Overview",
                "Facility Request",
                "Sources and Uses",
                "Financial Analysis",
                "Collateral and Support",
                "Risk Rating Rationale",
                "Covenants",
                "Conditions Precedent",
                "Recommendation",
            ),
        ),
        DocType(
            key="amlprocedure",
            name="BSA/AML Programme Procedure",
            abbrev="AML",
            id_grammar="AML",
            weight=1.4,
            authority="31 CFR Chapter X / FFIEC manual",
            system="SentryAML",
            sections=(
                "Regulatory Basis",
                "Customer Due Diligence",
                "Enhanced Due Diligence Triggers",
                "Transaction Monitoring Scenarios",
                "Alert Disposition",
                "Suspicious Activity Reporting",
                "Recordkeeping and Retention",
            ),
        ),
        DocType(
            key="modelrisk",
            name="Model Risk Documentation",
            abbrev="MRD",
            id_grammar="MRD",
            weight=1.1,
            authority="SR 11-7",
            system="RiskLedger",
            sections=(
                "Model Purpose and Use",
                "Conceptual Soundness",
                "Data Inputs and Quality",
                "Assumptions and Limitations",
                "Outcomes Analysis",
                "Independent Validation Findings",
                "Ongoing Monitoring Plan",
            ),
        ),
        DocType(
            key="regreport",
            name="Regulatory Reporting Control Narrative",
            abbrev="RRC",
            id_grammar="RRC",
            weight=1.2,
            authority="FFIEC Call Report / FR Y-9C",
            system="Ridgeport Core Banking",
            sections=(
                "Report and Schedule Scope",
                "Data Lineage",
                "Preparation Controls",
                "Reconciliation Procedures",
                "Review and Attestation",
                "Restatement Handling",
            ),
        ),
        DocType(
            key="paymentops",
            name="Payment Operations Standard",
            abbrev="PAY",
            id_grammar="PAY",
            weight=1.2,
            authority="NACHA rules / ISO 20022",
            system="Ridgeport Core Banking",
            sections=(
                "Payment Types in Scope",
                "Message Standards",
                "Cut-off Times and Windows",
                "Sanctions and Fraud Screening",
                "Exception and Return Handling",
                "Reconciliation",
            ),
        ),
        DocType(
            key="dispute",
            name="Dispute and Chargeback Procedure",
            abbrev="DSP",
            id_grammar="DSP",
            weight=1.1,
            authority="Regulation E / network rules",
            system="Ridgeport Core Banking",
            sections=(
                "Dispute Intake",
                "Provisional Credit Rules",
                "Investigation Timeline",
                "Network Representment",
                "Customer Notification",
                "Loss Recognition",
            ),
        ),
        DocType(
            key="auditissue",
            name="Internal Audit Issue Record",
            abbrev="IAI",
            id_grammar="IAI",
            weight=1.0,
            authority="Internal audit charter / IIA standards",
            system="RiskLedger",
            sections=(
                "Issue Description",
                "Root Cause",
                "Risk Rating",
                "Management Action Plan",
                "Target Date and Owner",
                "Validation of Closure",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="riskrating",
            name="Internal risk rating scale",
            authority="Credit policy",
            fmt="1–9 grade",
            codes=(
                ("1", "Minimal risk — cash secured or equivalent"),
                ("3", "Satisfactory — solid financial condition"),
                ("5", "Acceptable with monitoring"),
                ("6", "Special mention — potential weakness"),
                ("7", "Substandard — well-defined weakness"),
                ("8", "Doubtful — collection highly questionable"),
                ("9", "Loss — uncollectible"),
            ),
        ),
        CodeSystem(
            key="regulation",
            name="US banking regulation",
            authority="Federal Reserve / CFPB",
            fmt="Regulation letter",
            codes=(
                ("Reg B", "Equal Credit Opportunity Act"),
                ("Reg CC", "Availability of funds and collection of cheques"),
                ("Reg DD", "Truth in Savings"),
                ("Reg E", "Electronic Fund Transfers"),
                ("Reg Z", "Truth in Lending"),
                ("HMDA", "Home Mortgage Disclosure Act"),
                ("CRA", "Community Reinvestment Act"),
            ),
        ),
        CodeSystem(
            key="iso20022",
            name="ISO 20022 message",
            authority="ISO",
            fmt="four-letter.three-digit.two-digit",
            codes=(
                ("pacs.008", "Financial institution to financial institution customer credit transfer"),
                ("pacs.002", "Payment status report"),
                ("pain.001", "Customer credit transfer initiation"),
                ("camt.053", "Bank to customer statement"),
                ("camt.056", "Payment cancellation request"),
            ),
        ),
    ),
    workflows=(
        Workflow(
            key="loan",
            name="Loan origination",
            states=("Application", "Underwriting", "Credit approval",
                    "Documentation", "Funding", "Servicing", "Paid off"),
            terminal=("Paid off",),
        ),
        Workflow(
            key="amlalert",
            name="AML alert disposition",
            states=("Alert generated", "Triage", "Investigation",
                    "SAR filed", "Closed no action"),
            terminal=("SAR filed", "Closed no action"),
        ),
    ),
    lexicon=(
        "KYC", "CDD", "EDD", "SAR", "CTR", "OFAC", "PD", "LGD", "EAD",
        "covenant", "LTV", "DSCR", "RWA", "LCR", "NSFR", "SR 11-7",
        "call report", "three lines of defence", "risk appetite",
        "special mention", "substandard", "tie-out",
    ),
    subjects=(
        "commercial real estate concentration", "structured trade finance",
        "beneficial ownership verification", "politically exposed persons",
        "cash-intensive business monitoring", "wire transfer screening",
        "loan covenant breach", "appraisal review",
        "allowance for credit losses", "interest rate risk in the banking book",
        "deposit beta assumptions", "third-party risk assessment",
        "model back-testing", "regulatory reporting restatement",
        "cheque fraud pattern", "elder financial exploitation",
        "trade-based money laundering", "syndicated facility participation",
        "collateral perfection", "credit exception approval",
    ),
    sites=(
        "Head Office — Ridgeport", "Operations Centre East",
        "Commercial Lending Centre", "Financial Crimes Unit",
        "Branch Network — Region 2",
    ),
    ontology=(
        ("Borrower", "REQUESTS", "Facility"),
        ("Facility", "ASSESSED_IN", "CreditMemo"),
        ("CreditMemo", "ASSIGNS", "RiskRating"),
        ("Facility", "CONSTRAINED_BY", "Covenant"),
        ("Alert", "INVESTIGATED_UNDER", "AMLProcedure"),
        ("Alert", "ESCALATES_TO", "SuspiciousActivityReport"),
        ("Model", "VALIDATED_BY", "IndependentValidation"),
        ("AuditIssue", "REMEDIATED_BY", "ManagementAction"),
        ("Payment", "FORMATTED_AS", "ISO20022Message"),
    ),
    questions=(
        "What triggers enhanced due diligence on a cash-intensive business?",
        "Which covenants are standard on commercial real estate facilities?",
        "How are model validation findings tracked to closure?",
        "What is the escalation path when a transaction monitoring alert suggests structuring?",
        "Which risk ratings require credit committee approval rather than delegated authority?",
    ),
)


ASSURANCE = Pack(
    slug="q-assurance",
    spine="engagement",
    tenant="Q-Assurance",
    industry="External Audit and Assurance",
    tagline="Registered public accounting firm · 240 engagements",
    accent="#667085",
    units=(
        "Assurance Practice",
        "Engagement Teams",
        "Quality and Risk Management",
        "Independence",
        "National Office — Technical",
        "Engagement Quality Review",
        "Attestation Services",
        "Learning and Methodology",
    ),
    roles=(
        "Engagement Partner",
        "Engagement Quality Reviewer",
        "Senior Manager",
        "Audit Manager",
        "In-Charge Senior",
        "Audit Associate",
        "Director of Quality and Risk",
        "National Office Technical Partner",
    ),
    systems=(
        "Thornbury Engage",
        "Thornbury Workpapers",
        "ConfirmBridge",
        "MethodHub",
    ),
    doc_types=(
        DocType(
            key="planning",
            name="Audit Planning Memorandum",
            abbrev="APM",
            id_grammar="APM",
            weight=1.4,
            authority="AS 2101 / ISA 300",
            system="Thornbury Engage",
            sections=(
                "Engagement Background",
                "Scope and Reporting Objectives",
                "Understanding of the Entity",
                "Materiality Determination",
                "Significant Risks",
                "Planned Audit Approach",
                "Team Composition and Supervision",
                "Timetable",
            ),
        ),
        DocType(
            key="riskassess",
            name="Risk Assessment Working Paper",
            abbrev="RAW",
            id_grammar="RA",
            weight=1.5,
            authority="AS 2110 / ISA 315 (Revised 2019)",
            system="Thornbury Workpapers",
            sections=(
                "Assertion Under Consideration",
                "Inherent Risk Factors",
                "Control Environment Considerations",
                "Risk of Material Misstatement",
                "Significant Risk Determination",
                "Planned Response",
            ),
        ),
        DocType(
            key="controls",
            name="Control Walkthrough and Test",
            abbrev="CWT",
            id_grammar="CT",
            weight=1.6,
            authority="AS 2201 / ISA 330",
            system="Thornbury Workpapers",
            sections=(
                "Process and Control Description",
                "Control Objective",
                "Walkthrough Performed",
                "Design Effectiveness Conclusion",
                "Test of Operating Effectiveness",
                "Sample Selection Basis",
                "Exceptions Noted",
                "Conclusion",
            ),
        ),
        DocType(
            key="substantive",
            name="Substantive Procedure Working Paper",
            abbrev="SPW",
            id_grammar="SP",
            weight=1.5,
            authority="AS 1105 / ISA 500",
            system="Thornbury Workpapers",
            sections=(
                "Account Balance and Assertion",
                "Procedure Performed",
                "Population and Sampling",
                "Evidence Obtained",
                "Tickmark Legend",
                "Differences Identified",
                "Conclusion",
            ),
        ),
        DocType(
            key="materiality",
            name="Materiality Determination Memo",
            abbrev="MDM",
            id_grammar="MM",
            weight=1.0,
            authority="AS 2105 / ISA 320",
            system="Thornbury Engage",
            sections=(
                "Benchmark Selection",
                "Overall Materiality",
                "Performance Materiality",
                "Clearly Trivial Threshold",
                "Revision During the Audit",
                "Rationale",
            ),
        ),
        DocType(
            key="soc",
            name="SOC 2 Readiness Assessment",
            abbrev="SOC",
            id_grammar="SOC",
            weight=1.2,
            authority="AT-C 205 / Trust Services Criteria",
            system="Thornbury Engage",
            sections=(
                "System Description Scope",
                "Trust Services Categories",
                "Common Criteria Mapping",
                "Control Gaps Identified",
                "Remediation Recommendations",
                "Readiness Conclusion",
            ),
        ),
        DocType(
            key="eqr",
            name="Engagement Quality Review Record",
            abbrev="EQR",
            id_grammar="EQ",
            weight=0.9,
            authority="AS 1220 / ISQM 2",
            system="Thornbury Engage",
            sections=(
                "Reviewer Eligibility and Objectivity",
                "Matters Reviewed",
                "Significant Judgements Evaluated",
                "Discussion with Engagement Partner",
                "Unresolved Matters",
                "Concurring Approval",
            ),
        ),
        DocType(
            key="quality",
            name="Quality Management Response",
            abbrev="QMR",
            id_grammar="QM",
            weight=1.0,
            authority="ISQM 1 / SQMS 1",
            system="MethodHub",
            sections=(
                "Quality Objective",
                "Quality Risk Identified",
                "Response Designed",
                "Implementation Evidence",
                "Monitoring Activity",
                "Remediation of Deficiencies",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="pcaob",
            name="PCAOB auditing standard",
            authority="PCAOB",
            fmt="AS NNNN",
            codes=(
                ("AS 1105", "Audit evidence"),
                ("AS 1215", "Audit documentation"),
                ("AS 1220", "Engagement quality review"),
                ("AS 2101", "Audit planning"),
                ("AS 2105", "Consideration of materiality"),
                ("AS 2110", "Identifying and assessing risks of material misstatement"),
                ("AS 2201", "Audit of internal control over financial reporting"),
                ("AS 2301", "The auditor's responses to the risks of material misstatement"),
                ("AS 2401", "Consideration of fraud in a financial statement audit"),
                ("AS 2805", "Management representations"),
                ("AS 3101", "The auditor's report on financial statements"),
            ),
        ),
        CodeSystem(
            key="isa",
            name="International Standard on Auditing",
            authority="IAASB",
            fmt="ISA NNN",
            codes=(
                ("ISA 240", "The auditor's responsibilities relating to fraud"),
                ("ISA 300", "Planning an audit of financial statements"),
                ("ISA 315", "Identifying and assessing the risks of material misstatement"),
                ("ISA 320", "Materiality in planning and performing an audit"),
                ("ISA 330", "The auditor's responses to assessed risks"),
                ("ISA 500", "Audit evidence"),
                ("ISA 530", "Audit sampling"),
                ("ISA 570", "Going concern"),
                ("ISA 700", "Forming an opinion and reporting on financial statements"),
                ("ISA 701", "Communicating key audit matters"),
            ),
        ),
        CodeSystem(
            key="tsc",
            name="Trust Services Criteria category",
            authority="AICPA",
            fmt="category name",
            codes=(
                ("Security", "Common criteria — required in every SOC 2"),
                ("Availability", "System is available for operation and use"),
                ("Processing Integrity", "Processing is complete, valid, accurate and timely"),
                ("Confidentiality", "Information designated confidential is protected"),
                ("Privacy", "Personal information is handled per commitments"),
            ),
        ),
        CodeSystem(
            key="tickmark",
            name="Workpaper tickmark",
            authority="Firm methodology",
            fmt="symbol legend",
            codes=(
                ("F", "Footed and cross-footed"),
                ("TB", "Agreed to trial balance"),
                ("GL", "Agreed to general ledger detail"),
                ("PBC", "Provided by client"),
                ("CX", "Confirmed externally"),
                ("AJE", "Adjusting journal entry proposed"),
                ("PAJE", "Passed adjustment, below threshold"),
            ),
        ),
    ),
    workflows=(
        Workflow(
            key="engagement",
            name="Engagement lifecycle",
            states=("Acceptance", "Planning", "Risk assessment",
                    "Controls testing", "Substantive testing", "Completion",
                    "Quality review", "Report issued", "Archived"),
            terminal=("Archived",),
        ),
        Workflow(
            key="workpaper",
            name="Workpaper review",
            states=("Prepared", "Under review", "Review notes cleared",
                    "Signed off", "Locked"),
            terminal=("Locked",),
        ),
    ),
    lexicon=(
        "tie-out", "tickmark", "PBC", "lead schedule", "RMM",
        "performance materiality", "walkthrough", "TOC", "substantive",
        "sampling", "AJE", "PAJE", "KAM", "CAM", "going concern",
        "EQR", "clean opinion", "management letter", "roll-forward",
    ),
    subjects=(
        "revenue recognition cut-off", "inventory existence observation",
        "goodwill impairment assumptions", "expected credit loss modelling",
        "related party completeness", "management override of controls",
        "journal entry testing", "IT general controls",
        "user access recertification", "change management approval",
        "third-party service organisation reliance",
        "going concern assessment", "contingent liability disclosure",
        "share-based payment valuation", "lease classification",
        "capitalisation of development costs", "accrual completeness",
        "bank confirmation response", "segment disclosure accuracy",
        "subsequent events review",
    ),
    sites=(
        "Thornbury — Head Office", "Regional Office North",
        "Regional Office Coastal", "Delivery Centre",
    ),
    ontology=(
        ("Engagement", "PLANNED_IN", "PlanningMemorandum"),
        ("Engagement", "ASSESSES", "RiskOfMaterialMisstatement"),
        ("RiskOfMaterialMisstatement", "RESPONDED_TO_BY", "AuditProcedure"),
        ("AuditProcedure", "DOCUMENTED_IN", "Workpaper"),
        ("Workpaper", "REVIEWED_BY", "Role"),
        ("Control", "TESTED_BY", "ControlTest"),
        ("ControlTest", "IDENTIFIES", "Exception"),
        ("Engagement", "SUBJECT_TO", "EngagementQualityReview"),
        ("AuditProcedure", "GOVERNED_BY", "AuditingStandard"),
    ),
    questions=(
        "How is performance materiality set relative to overall materiality?",
        "Which significant risks require a substantive response regardless of control reliance?",
        "What must an engagement quality reviewer evaluate before the report is released?",
        "How are control exceptions evaluated for severity?",
        "Which Trust Services Criteria are in scope for a SOC 2 covering availability?",
    ),
)


CRUISE = Pack(
    slug="q-cruise",
    spine="vessel",
    tenant="Q-Cruise",
    industry="Cruise Line Marine and Hotel Operations",
    tagline="9 vessels · 24,000 lower berths · global deployment",
    accent="#0EA5E9",
    units=(
        "Marine Operations",
        "Deck Department",
        "Engine Department",
        "Hotel Operations",
        "Food and Beverage",
        "Housekeeping",
        "Guest Services",
        "Shore Excursions",
        "Environmental Compliance",
        "Safety and Security",
        "Port Operations",
        "Fleet Technical",
        "Medical Centre",
    ),
    roles=(
        "Master",
        "Staff Captain",
        "Chief Engineer",
        "Chief Officer",
        "Safety Officer",
        "Environmental Officer",
        "Ship Security Officer",
        "Hotel Director",
        "Executive Chef",
        "Guest Relations Manager",
        "Designated Person Ashore",
    ),
    systems=(
        "Meridian Fleet PMS",
        "VoyageDesk",
        "GuestFolio",
        "SafeSea Reporting",
    ),
    doc_types=(
        DocType(
            key="sms",
            name="Safety Management System Procedure",
            abbrev="SMS",
            id_grammar="SMS",
            weight=1.5,
            authority="ISM Code",
            system="SafeSea Reporting",
            sections=(
                "Purpose and Scope",
                "Responsibility and Authority",
                "Shipboard Procedure",
                "Emergency Preparedness",
                "Reporting Requirements",
                "Verification and Review",
            ),
        ),
        DocType(
            key="drill",
            name="Drill and Muster Record",
            abbrev="DRL",
            id_grammar="DRL",
            weight=1.3,
            authority="SOLAS Chapter III",
            system="SafeSea Reporting",
            sections=(
                "Drill Type and Scenario",
                "Participation Record",
                "Equipment Deployed",
                "Timings Achieved",
                "Observations and Shortfalls",
                "Corrective Actions",
            ),
        ),
        DocType(
            key="psc",
            name="Port State Control Deficiency Response",
            abbrev="PSC",
            id_grammar="PSC",
            weight=1.2,
            authority="Paris MOU / Tokyo MOU / USCG",
            system="SafeSea Reporting",
            sections=(
                "Inspection Details",
                "Deficiency Codes Raised",
                "Immediate Actions Taken",
                "Root Cause",
                "Rectification Evidence",
                "Fleet-Wide Applicability",
            ),
        ),
        DocType(
            key="environmental",
            name="Environmental Compliance Procedure",
            abbrev="ENV",
            id_grammar="ENV",
            weight=1.3,
            authority="MARPOL Annexes I–VI",
            system="SafeSea Reporting",
            sections=(
                "Applicable Annex and Regulation",
                "Special Area Requirements",
                "Operational Controls",
                "Record Book Entries",
                "Monitoring and Sampling",
                "Non-Conformity Reporting",
            ),
        ),
        DocType(
            key="pms",
            name="Planned Maintenance Work Order",
            abbrev="PMS",
            id_grammar="WO",
            weight=1.6,
            authority="Class survey requirements",
            system="Meridian Fleet PMS",
            sections=(
                "Equipment and Location",
                "Maintenance Task",
                "Interval Basis",
                "Isolation and Permit Requirements",
                "Spares and Consumables",
                "Work Performed",
                "Verification",
            ),
        ),
        DocType(
            key="vsp",
            name="Vessel Sanitation Programme Standard",
            abbrev="VSP",
            id_grammar="VSP",
            weight=1.2,
            authority="CDC Vessel Sanitation Program",
            system="SafeSea Reporting",
            sections=(
                "Area and Equipment Scope",
                "Temperature and Time Controls",
                "Cleaning and Sanitising",
                "Potable Water Management",
                "Outbreak Prevention and Response",
                "Inspection Readiness",
            ),
        ),
        DocType(
            key="voyage",
            name="Voyage Plan and Port Brief",
            abbrev="VOY",
            id_grammar="VOY",
            weight=1.4,
            authority="SOLAS Chapter V",
            system="VoyageDesk",
            sections=(
                "Appraisal",
                "Planning",
                "Port Particulars and Restrictions",
                "Navigational Hazards",
                "Execution Notes",
                "Monitoring Requirements",
                "Contingency and Abort Points",
            ),
        ),
        DocType(
            key="incident",
            name="Incident and Near-Miss Report",
            abbrev="INC",
            id_grammar="INC",
            weight=1.4,
            authority="ISM Code 9.1",
            system="SafeSea Reporting",
            sections=(
                "Event Description",
                "Location and Conditions",
                "Persons Involved",
                "Immediate Consequences",
                "Causal Analysis",
                "Corrective and Preventive Actions",
                "Lessons Disseminated",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="pscdef",
            name="Port State Control deficiency code",
            authority="Paris MOU",
            fmt="five-digit numeric",
            codes=(
                ("01220", "Certificates and documentation — deficient"),
                ("02106", "Structural condition — corrosion"),
                ("04109", "Emergency systems — emergency lighting"),
                ("07105", "Fire safety — fire doors"),
                ("07110", "Fire safety — fire detection system"),
                ("09220", "ISM — maintenance of the ship and equipment"),
                ("11101", "Life-saving appliances — lifeboats"),
                ("14108", "Pollution prevention — oil record book"),
                ("18302", "Labour conditions — hours of rest"),
                ("99102", "Other — SOLAS operational"),
            ),
        ),
        CodeSystem(
            key="convention",
            name="IMO convention",
            authority="International Maritime Organization",
            fmt="convention name",
            codes=(
                ("SOLAS", "Safety of Life at Sea"),
                ("MARPOL", "Prevention of Pollution from Ships"),
                ("ISM", "International Safety Management Code"),
                ("ISPS", "International Ship and Port Facility Security Code"),
                ("MLC 2006", "Maritime Labour Convention"),
                ("STCW", "Standards of Training, Certification and Watchkeeping"),
                ("BWM", "Ballast Water Management Convention"),
            ),
        ),
        CodeSystem(
            key="survey",
            name="Classification survey type",
            authority="Classification society rules",
            fmt="survey name",
            codes=(
                ("Annual", "Annual survey within the anniversary window"),
                ("Intermediate", "Intermediate survey, second or third year"),
                ("Renewal", "Five-yearly renewal or special survey"),
                ("Docking", "Bottom survey in dry dock"),
                ("Occasional", "Survey following damage or repair"),
            ),
        ),
    ),
    workflows=(
        Workflow(
            key="defect",
            name="Defect and work order",
            states=("Reported", "Assessed", "Planned", "In progress",
                    "Awaiting spares", "Completed", "Verified"),
            terminal=("Verified",),
        ),
        Workflow(
            key="psc",
            name="Port State Control deficiency",
            states=("Raised", "Action code assigned", "Rectification in progress",
                    "Evidence submitted", "Closed"),
            terminal=("Closed",),
        ),
    ),
    lexicon=(
        "SMS", "DOC", "SMC", "muster", "drill", "PSC", "detention",
        "class survey", "drydock", "bunkering", "ballast water",
        "Oil Record Book", "NOR", "UN/LOCODE", "IMO number", "MOB",
        "turn day", "DPA", "hours of rest", "special area",
    ),
    subjects=(
        "lifeboat launch timing", "watertight door indication",
        "galley temperature logging", "potable water halogenation",
        "norovirus outbreak response", "oily water separator alarm",
        "garbage record book entry", "shore power connection",
        "tender operation in swell", "gangway security screening",
        "medical disembarkation", "man overboard drill",
        "fire damper inspection", "sewage treatment plant excursion",
        "hours of rest non-conformity", "provisions cold chain",
        "guest incident on excursion", "bunker delivery note discrepancy",
        "hull fouling inspection", "emergency generator load test",
    ),
    sites=(
        "MV Meridian Aurora", "MV Meridian Solace", "MV Meridian Vantage",
        "Fleet Operations Centre", "Port Agency — ZZ Terminal 3",
        "Dry Dock Facility North",
    ),
    ontology=(
        ("Vessel", "OPERATES", "Voyage"),
        ("Voyage", "CALLS_AT", "Port"),
        ("Vessel", "SUBJECT_TO", "Convention"),
        ("Inspection", "RAISES", "DeficiencyCode"),
        ("DeficiencyCode", "RECTIFIED_BY", "WorkOrder"),
        ("Equipment", "MAINTAINED_UNDER", "WorkOrder"),
        ("Drill", "SATISFIES", "SOLASRequirement"),
        ("Incident", "IDENTIFIES", "CausalFactor"),
        ("Procedure", "OWNED_BY", "Department"),
    ),
    questions=(
        "Which Port State Control deficiency codes recur across the fleet and what are the root causes?",
        "What drill timings must be achieved and how are shortfalls escalated?",
        "How are potable water halogenation records verified before a VSP inspection?",
        "What contingency points are set in a voyage plan for a constrained port approach?",
        "Which MARPOL special area requirements change the discharge controls?",
    ),
)


RETAIL = Pack(
    slug="q-retail",
    spine="vendor",
    tenant="Q-Retail",
    industry="Omnichannel Retail and Supply Chain",
    tagline="620 stores · 4 distribution centres · direct import",
    accent="#FF5004",
    units=(
        "Merchandising",
        "Planning and Allocation",
        "Supply Chain",
        "Distribution Operations",
        "Transportation",
        "Store Operations",
        "E-commerce",
        "Demand Planning",
        "Vendor Management",
        "Loss Prevention",
        "Inventory Control",
    ),
    roles=(
        "Vice President, Supply Chain",
        "Divisional Merchandise Manager",
        "Buyer",
        "Merchandise Planner",
        "Allocation Analyst",
        "Demand Planner",
        "Distribution Centre Manager",
        "Transportation Manager",
        "Vendor Compliance Analyst",
        "Store Operations Director",
    ),
    systems=(
        "Harbourfield ERP",
        "FlowWMS",
        "RouteCast TMS",
        "OrderMesh OMS",
    ),
    doc_types=(
        DocType(
            key="routing",
            name="Vendor Routing Guide Section",
            abbrev="VRG",
            id_grammar="VRG",
            weight=1.5,
            authority="Vendor compliance programme",
            system="Harbourfield ERP",
            sections=(
                "Scope and Applicability",
                "Carrier Selection and Routing",
                "Appointment Scheduling",
                "Labelling and Barcode Requirements",
                "EDI Requirements",
                "Packaging and Palletisation",
                "Chargeback Schedule",
            ),
        ),
        DocType(
            key="edispec",
            name="EDI Transaction Specification",
            abbrev="EDI",
            id_grammar="EDI",
            weight=1.3,
            authority="ASC X12 retail subset",
            system="Harbourfield ERP",
            sections=(
                "Transaction Purpose",
                "Segment Requirements",
                "Hierarchical Structure",
                "Qualifier Usage",
                "Acknowledgement Expectations",
                "Error Conditions",
                "Certification Process",
            ),
        ),
        DocType(
            key="dcsop",
            name="Distribution Centre Standard Operating Procedure",
            abbrev="DSP",
            id_grammar="DC",
            weight=1.6,
            authority="DC operations manual",
            system="FlowWMS",
            sections=(
                "Process Scope",
                "Safety Requirements",
                "Equipment and Systems",
                "Step-by-Step Procedure",
                "Exception Handling",
                "Productivity Standards",
                "Quality Checks",
            ),
        ),
        DocType(
            key="replen",
            name="Replenishment Policy",
            abbrev="RPL",
            id_grammar="RPL",
            weight=1.3,
            authority="Inventory policy committee",
            system="Harbourfield ERP",
            sections=(
                "Policy Objective",
                "Segmentation and Service Targets",
                "Forecast Inputs",
                "Safety Stock Calculation",
                "Reorder Logic",
                "Exception Review",
                "Performance Measurement",
            ),
        ),
        DocType(
            key="storeops",
            name="Store Operations Standard",
            abbrev="SOS",
            id_grammar="SO",
            weight=1.4,
            authority="Store operations manual",
            system="Harbourfield ERP",
            sections=(
                "Standard Purpose",
                "Daily Execution",
                "Roles and Coverage",
                "Systems and Devices",
                "Customer-Facing Requirements",
                "Compliance Verification",
            ),
        ),
        DocType(
            key="omni",
            name="Omnichannel Fulfilment Specification",
            abbrev="OMNI",
            id_grammar="OMN",
            weight=1.2,
            authority="Digital operations governance",
            system="OrderMesh OMS",
            sections=(
                "Fulfilment Node Types",
                "Sourcing Logic",
                "Inventory Availability Rules",
                "Pick, Pack and Handover",
                "Customer Communication",
                "Returns Path",
                "Service Level Measurement",
            ),
        ),
        DocType(
            key="import",
            name="Import and Customs Procedure",
            abbrev="IMP",
            id_grammar="IMP",
            weight=1.1,
            authority="Customs brokerage agreement",
            system="RouteCast TMS",
            sections=(
                "Incoterms Applied",
                "Documentation Set",
                "Classification and Duty",
                "Broker Instructions",
                "Container Handling",
                "Exception Escalation",
            ),
        ),
        DocType(
            key="shrink",
            name="Shrink and Loss Prevention Standard",
            abbrev="LP",
            id_grammar="LP",
            weight=1.1,
            authority="Loss prevention policy",
            system="Harbourfield ERP",
            sections=(
                "Loss Categories",
                "Detection Methods",
                "Cycle Count Programme",
                "Investigation Protocol",
                "Escalation Thresholds",
                "Reporting Cadence",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="x12retail",
            name="X12 retail transaction set",
            authority="ASC X12",
            fmt="three-digit set",
            codes=(
                ("810", "Invoice"),
                ("850", "Purchase order"),
                ("852", "Product activity data"),
                ("855", "Purchase order acknowledgement"),
                ("856", "Ship notice / manifest"),
                ("860", "Purchase order change request"),
                ("940", "Warehouse shipping order"),
                ("945", "Warehouse shipping advice"),
                ("997", "Functional acknowledgement"),
            ),
        ),
        CodeSystem(
            key="gs1",
            name="GS1 identification key",
            authority="GS1",
            fmt="key with mod-10 check digit",
            codes=(
                ("GTIN-13", "Global Trade Item Number, 13 digits"),
                ("GTIN-14", "Case-level trade item, 14 digits"),
                ("SSCC", "Serial Shipping Container Code, 18 digits"),
                ("GLN", "Global Location Number, 13 digits"),
                ("AI 00", "Application identifier for SSCC"),
                ("AI 01", "Application identifier for GTIN"),
                ("AI 10", "Application identifier for batch or lot"),
                ("AI 17", "Application identifier for expiry date"),
            ),
        ),
        CodeSystem(
            key="incoterms",
            name="Incoterms 2020",
            authority="International Chamber of Commerce",
            fmt="three-letter",
            codes=(
                ("EXW", "Ex works"),
                ("FCA", "Free carrier"),
                ("FOB", "Free on board"),
                ("CIF", "Cost, insurance and freight"),
                ("DAP", "Delivered at place"),
                ("DDP", "Delivered duty paid"),
            ),
        ),
    ),
    workflows=(
        Workflow(
            key="p2p",
            name="Purchase to receipt",
            states=("PO created", "PO acknowledged", "In production",
                    "Shipped", "In transit", "Received", "Invoiced", "Paid"),
            terminal=("Paid",),
        ),
        Workflow(
            key="fulfilment",
            name="Omnichannel fulfilment",
            states=("Ordered", "Sourced", "Allocated", "Picked", "Packed",
                    "Shipped", "Ready for collection", "Delivered", "Returned"),
            terminal=("Delivered", "Returned"),
        ),
    ),
    lexicon=(
        "OTB", "SKU", "ASN", "SSCC", "GTIN", "GLN", "chargeback",
        "routing guide", "BOPIS", "ship-from-store", "safety stock",
        "cycle count", "shrink", "S&OP", "DC", "cross-dock", "fill rate",
        "sell-through", "markdown", "on-hand", "lead time",
    ),
    subjects=(
        "advance ship notice accuracy", "carton label placement",
        "pallet build standards", "appointment no-show",
        "cross-dock flow-through", "peak season staffing",
        "returns disposition grading", "store replenishment cadence",
        "planogram compliance", "markdown cadence",
        "cold chain temperature excursion", "container demurrage",
        "duty classification dispute", "vendor chargeback dispute",
        "cycle count variance", "buy-online-pickup-in-store handover",
        "carrier capacity commitment", "safety stock recalculation",
        "forecast bias correction", "point-of-sale outage recovery",
    ),
    sites=(
        "DC North — Harbourfield", "DC Central", "DC Coastal",
        "Import Consolidation Centre", "Store 0142", "Store 0388",
        "E-commerce Fulfilment Node 2",
    ),
    ontology=(
        ("PurchaseOrder", "PLACED_WITH", "Vendor"),
        ("PurchaseOrder", "ACKNOWLEDGED_BY", "EDITransaction"),
        ("Shipment", "IDENTIFIED_BY", "SSCC"),
        ("Shipment", "RECEIVED_AT", "DistributionCentre"),
        ("Vendor", "GOVERNED_BY", "RoutingGuide"),
        ("Violation", "TRIGGERS", "Chargeback"),
        ("Item", "IDENTIFIED_BY", "GTIN"),
        ("Item", "REPLENISHED_UNDER", "ReplenishmentPolicy"),
        ("Order", "FULFILLED_BY", "FulfilmentNode"),
    ),
    questions=(
        "What are the carton labelling requirements and which chargebacks apply when they are missed?",
        "How is safety stock calculated for seasonal items?",
        "Which EDI transactions must a vendor certify before first shipment?",
        "How does ship-from-store sourcing decide between nodes?",
        "What triggers a cycle count investigation rather than a routine adjustment?",
    ),
)


QUALITY = Pack(
    slug="q-quality",
    spine="requirement",
    tenant="Q-Quality",
    industry="Quality Engineering and Software Testing",
    tagline="Test centre of excellence · automation · performance · security",
    accent="#6D5BD0",
    units=(
        "Test Centre of Excellence",
        "Functional Testing",
        "Test Automation",
        "Performance Engineering",
        "Security Testing",
        "Accessibility Testing",
        "Test Data Management",
        "Test Environments",
        "Release Quality Gates",
        "User Acceptance Coordination",
    ),
    roles=(
        "Head of Quality Engineering",
        "Test Architect",
        "Test Manager",
        "Automation Lead",
        "Performance Test Engineer",
        "Security Test Engineer",
        "Accessibility Specialist",
        "Test Data Manager",
        "Release Manager",
        "UAT Coordinator",
    ),
    systems=(
        "Axiom TestHub",
        "Axiom DefectTrack",
        "PipelineGate CI",
        "DataForge TDM",
    ),
    doc_types=(
        DocType(
            key="strategy",
            name="Organisational Test Strategy",
            abbrev="OTS",
            id_grammar="OTS",
            weight=1.0,
            authority="ISO/IEC/IEEE 29119-3",
            system="Axiom TestHub",
            sections=(
                "Scope and Context",
                "Test Levels and Types",
                "Risk-Based Prioritisation",
                "Automation Strategy",
                "Environment and Data Strategy",
                "Entry and Exit Criteria",
                "Metrics and Reporting",
            ),
        ),
        DocType(
            key="testplan",
            name="Project Test Plan",
            abbrev="TP",
            id_grammar="TP",
            weight=1.4,
            authority="ISO/IEC/IEEE 29119-3 clause 7",
            system="Axiom TestHub",
            sections=(
                "Context of Testing",
                "Test Objectives",
                "Scope — In and Out",
                "Risk Register",
                "Test Approach",
                "Entry, Exit, Suspension and Resumption Criteria",
                "Deliverables",
                "Environment and Data Needs",
                "Schedule and Staffing",
            ),
        ),
        DocType(
            key="testdesign",
            name="Test Design Specification",
            abbrev="TDS",
            id_grammar="TDS",
            weight=1.6,
            authority="ISO/IEC/IEEE 29119-3 clause 10",
            system="Axiom TestHub",
            sections=(
                "Feature Under Test",
                "Test Conditions Derived",
                "Design Techniques Applied",
                "Coverage Items",
                "Traceability to Requirements",
                "Test Case Outline",
            ),
        ),
        DocType(
            key="rtm",
            name="Requirements Traceability Matrix",
            abbrev="RTM",
            id_grammar="RTM",
            weight=1.2,
            authority="Test governance",
            system="Axiom TestHub",
            sections=(
                "Traceability Scope",
                "Requirement to Condition Mapping",
                "Condition to Test Case Mapping",
                "Test Case to Defect Mapping",
                "Coverage Gaps",
                "Sign-Off",
            ),
        ),
        DocType(
            key="defectstd",
            name="Defect Management Standard",
            abbrev="DMS",
            id_grammar="DMS",
            weight=1.3,
            authority="Test governance / ISTQB terminology",
            system="Axiom DefectTrack",
            sections=(
                "Defect Lifecycle States",
                "Severity Definitions",
                "Priority Definitions",
                "Triage Process",
                "Reopen and Rejection Rules",
                "Escape Analysis",
                "Reporting Metrics",
            ),
        ),
        DocType(
            key="perf",
            name="Performance Test Specification",
            abbrev="PTS",
            id_grammar="PTS",
            weight=1.3,
            authority="Non-functional requirements baseline",
            system="Axiom TestHub",
            sections=(
                "Performance Objectives",
                "Workload Model",
                "Transaction Mix",
                "Ramp Profile",
                "Environment Fidelity",
                "Acceptance Thresholds",
                "Monitoring and Instrumentation",
                "Results and Bottleneck Analysis",
            ),
        ),
        DocType(
            key="security",
            name="Security Test Plan",
            abbrev="STP",
            id_grammar="STP",
            weight=1.2,
            authority="OWASP ASVS",
            system="Axiom TestHub",
            sections=(
                "Threat Model Summary",
                "ASVS Verification Level",
                "Test Scope and Rules of Engagement",
                "Authentication and Session Testing",
                "Access Control Testing",
                "Input Validation Testing",
                "Findings and Severity",
                "Retest Evidence",
            ),
        ),
        DocType(
            key="a11y",
            name="Accessibility Conformance Assessment",
            abbrev="ACA",
            id_grammar="ACA",
            weight=1.1,
            authority="WCAG 2.2 Level AA",
            system="Axiom TestHub",
            sections=(
                "Scope of Assessment",
                "Conformance Target",
                "Testing Method",
                "Success Criteria Results",
                "Defects Raised",
                "Remediation Guidance",
                "Conformance Statement",
            ),
        ),
        DocType(
            key="gate",
            name="Release Quality Gate Definition",
            abbrev="RQG",
            id_grammar="RQG",
            weight=1.2,
            authority="CI/CD governance",
            system="PipelineGate CI",
            sections=(
                "Gate Purpose",
                "Stage in Pipeline",
                "Measures Evaluated",
                "Thresholds",
                "Blocking Behaviour",
                "Override Authority",
                "Evidence Retained",
            ),
        ),
    ),
    code_systems=(
        CodeSystem(
            key="29119",
            name="ISO/IEC/IEEE 29119-3 document type",
            authority="ISO/IEC/IEEE",
            fmt="document name",
            codes=(
                ("Test Policy", "Organisational testing principles"),
                ("Organisational Test Strategy", "Cross-project testing approach"),
                ("Test Plan", "Project or sub-process test planning"),
                ("Test Status Report", "Periodic progress against plan"),
                ("Test Completion Report", "Summary at the end of testing"),
                ("Test Design Specification", "Test conditions and coverage items"),
                ("Test Case Specification", "Inputs, expected results, preconditions"),
                ("Test Procedure Specification", "Execution sequence"),
                ("Test Execution Log", "Chronological record of execution"),
                ("Incident Report", "Anomaly requiring investigation"),
            ),
        ),
        CodeSystem(
            key="severity",
            name="Defect severity",
            authority="Defect management standard",
            fmt="S1–S4",
            codes=(
                ("S1", "Critical — core function unusable, no workaround"),
                ("S2", "High — major function impaired, workaround costly"),
                ("S3", "Medium — function impaired with acceptable workaround"),
                ("S4", "Low — cosmetic or minor inconvenience"),
            ),
        ),
        CodeSystem(
            key="wcag",
            name="WCAG 2.2 success criterion",
            authority="W3C",
            fmt="N.N.N with level",
            codes=(
                ("1.1.1", "Non-text content (A)"),
                ("1.4.3", "Contrast minimum (AA)"),
                ("1.4.11", "Non-text contrast (AA)"),
                ("2.1.1", "Keyboard (A)"),
                ("2.4.7", "Focus visible (AA)"),
                ("2.5.8", "Target size minimum (AA)"),
                ("3.3.1", "Error identification (A)"),
                ("4.1.2", "Name, role, value (A)"),
            ),
        ),
    ),
    workflows=(
        Workflow(
            key="defect",
            name="Defect lifecycle",
            states=("New", "Triaged", "Assigned", "In progress", "Fixed",
                    "Ready for retest", "Verified", "Closed", "Reopened",
                    "Rejected", "Deferred"),
            terminal=("Closed", "Rejected", "Deferred"),
        ),
        Workflow(
            key="stlc",
            name="Test lifecycle",
            states=("Requirement analysis", "Test planning", "Test design",
                    "Environment setup", "Execution", "Closure"),
            terminal=("Closure",),
        ),
    ),
    lexicon=(
        "RTM", "entry criteria", "exit criteria", "shift-left", "smoke",
        "sanity", "regression suite", "flaky test", "defect leakage",
        "containment", "quality gate", "test pyramid", "DoD", "triage",
        "severity", "priority", "UAT", "coverage", "ASVS", "WCAG",
    ),
    subjects=(
        "login session expiry", "payment retry idempotency",
        "search relevance ranking", "bulk upload validation",
        "concurrent edit conflict", "report export pagination",
        "role permission boundary", "password reset flow",
        "third-party API timeout", "database connection pool exhaustion",
        "cache invalidation on update", "notification delivery ordering",
        "keyboard-only navigation", "screen reader announcement",
        "colour contrast on disabled controls", "rate limit enforcement",
        "audit log completeness", "time zone handling at boundaries",
        "file upload content sniffing", "soak test memory growth",
    ),
    sites=(
        "TCoE — Delivery Hub", "Automation Lab", "Performance Lab",
        "Security Test Cell", "Accessibility Lab", "UAT Environment",
    ),
    ontology=(
        ("Requirement", "COVERED_BY", "TestCondition"),
        ("TestCondition", "REALISED_BY", "TestCase"),
        ("TestCase", "EXECUTED_IN", "TestRun"),
        ("TestRun", "RAISES", "Defect"),
        ("Defect", "ASSIGNED_SEVERITY", "SeverityLevel"),
        ("Defect", "TRACED_TO", "Requirement"),
        ("QualityGate", "EVALUATES", "Measure"),
        ("TestPlan", "GOVERNED_BY", "TestStrategy"),
        ("Assessment", "VERIFIES", "SuccessCriterion"),
    ),
    questions=(
        "What are the exit criteria for system test and who can waive them?",
        "How is defect severity distinguished from priority during triage?",
        "Which WCAG success criteria fail most often and what is the remediation pattern?",
        "What workload model does the performance specification use for peak trading?",
        "How does a quality gate decide to block a release rather than warn?",
    ),
)
